name: EndlessFlow
version: 2.0
main: com.hawkfalcon.EndlessFlow.EndlessFlow
commands:
    ef:
        description: everything
        usage: /ef
        
permissions: 
    endlessflow.*:
        description: Allows use of /ef
        default: OP
